import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareMarkdown,createBookshelfHandler} from '../api/bookshelf.js';
const env={RAG_IMPORT_TOKEN:'test-secret',SUPABASE_URL:'https://example.invalid',SUPABASE_SECRET_KEY:'test',GEMINI_API_KEY:'test'};
function response(){return {code:200,setHeader(){},status(c){this.code=c;return this;},json(d){this.data=d;return this;}};}
test('markdown validation, headings and long lines',()=>{assert.throws(()=>prepareMarkdown('../bad.md','x'));assert.throws(()=>prepareMarkdown('x.md',''));assert.throws(()=>prepareMarkdown('x.md','a'.repeat(40001)));const p=prepareMarkdown('number_1.md','# 数字1\n自分で決める\n## 龍導\n主体的に動く');assert.equal(p.title,'数字1');assert.equal(p.chunks.length,2);assert.equal(prepareMarkdown('long.md','a'.repeat(8000)).chunks.length,4);});
test('wrong secret makes no external requests',async()=>{const res=response();await createBookshelfHandler({env,fetcher:()=>{throw Error('unexpected');}})({method:'POST',body:{token:'bad',action:'list'}},res);assert.equal(res.code,401);});
test('embedding failure never replaces stored document',async()=>{const calls=[];const res=response();await createBookshelfHandler({env,fetcher:async(url)=>{calls.push(url);return {ok:true,json:async()=>[{id:'existing'}]};},embedder:async()=>{throw Error('embedding failed');}})({method:'POST',body:{token:'test-secret',action:'save',id:'11111111-1111-4111-8111-111111111111',name:'x.md',content:'# One\nHello'}},res);assert.equal(res.code,502);assert.equal(calls.length,1);assert.ok(!calls[0].includes('rpc'));});
test('save uses atomic registration with new UUID',async()=>{let body;const res=response();await createBookshelfHandler({env,fetcher:async(url,opts)=>{body=JSON.parse(opts.body);return {ok:true,status:204};},embedder:async()=>Array(768).fill(0.1)})({method:'POST',body:{token:'test-secret',action:'save',name:'x.md',content:'# One\nHello'}},res);assert.equal(res.code,200);assert.equal(body.p_metadata.origin,'bookshelf');assert.equal(body.p_chunks[0].embedding.length,768);assert.match(body.p_document_id,/^[a-f0-9-]{36}$/);});
test('removal limited to shelf documents',async()=>{const res=response();let calls=0;await createBookshelfHandler({env,fetcher:async()=>{calls++;return {ok:true,json:async()=>[]};}})({method:'POST',body:{token:'test-secret',action:'remove',id:'11111111-1111-4111-8111-111111111111'}},res);assert.equal(res.code,404);assert.equal(calls,1);});
